server:
  port: 8181

logging:
  level:
    com.food.ordering.system: info

spring:
  datasource:
    url: jdbc:mysql://root:qWYxHqFFHmJrrubhpoJIjPTlqEWbqUCl@switchback.proxy.rlwy.net:52537/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: {DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql

snow-flake:
  datacenter_id: 1
  machine_id: 1

loan-service:
  loan-disbursement-topic-name: LOAN_DISBURSEMENT_TOPIC
  loan-disbursed-topic-name: LOAN_DISBURSED_TOPIC
  outbox-scheduler-fixed-rate: 1000
  outbox-scheduler-initial-delay: 5000

kafka-consumer-config:
  consumer-group-id: payment-topic-consumer